### ISSUE TITLE
Do not use `apt-get install -q -y` in a tutorial

### ISSUE THREAD

**Issue by peci1** [scole02/Guide2Gazebo#1]
https://github.com/scole02/Guide2Gazebo/blob/ec70c4e1aef426d92dc99e8d5b255225c6634599/README.md?plain=1#L55

Please remove the `-q` and `-y` from the apt install command. This is a tutorial for people who often do not know what they are doing, and running this kind of commands can completely break their system. Let APT tell them what it is about to do and let the user decide if it seems reasonable.

**Comment by scole02** [comment]
Ah yes good point!
